services:
  db:
    image: postgres:14-alpine
    container_name: db-staging
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: staging
    volumes:
      - staging:/var/lib/postgresql/data
      - "./data:/data" # mapping

  db-core:
    image: postgres:14-alpine
    container_name: db-core
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: core
    volumes:
      - core:/var/lib/postgresql/data

volumes:
  staging:
  core: ## volume logique